-   id: grepkin
    name: grepkin
    description: Validate Gherkin in test code against reference Feature files
    entry: grepkin
    language: rust
    pass_filenames: false
-   id: grepkin-dockerfile
    name: grepkin-dockerfile
    description: Validate Gherkin in test code against reference Feature files via Dockerfile
    entry: /grepkin
    language: docker
    pass_filenames: false
