-   id: gherkin-testcomments
    name: gherkin-testcomments
    description: Validate files against bleeeh
    entry: gherkin_testcomments
    language: rust
    pass_filenames: false
-   id: gherkin-testcomments-dockerfile
    name: gherkin-testcomments-dockerfile
    description: Validate files against bleeeh via Dockerfile
    entry: /gherkin_testcomments
    language: docker
    pass_filenames: false
