"""Test auto-generated by Grepkin, referencing a Gherkin feature file
{% if feature.path is defined -%}
From reference feature-file at {{feature.path}}
{% endif %}

{# Note: Tera is limited: split description on newlines, then prefix first with FEATURE kw and indent rest -#}
Feature: {{feature.name}}
{%set descs = feature.description | split(pat="\n") -%}
{% for desc_line in descs-%}
  {{desc_line}}
{% endfor -%}
"""
{# Space out the feature and the scenarios=tests #}
{% for scenario in feature.scenarios %}
def test_{{scenario.name | lower | replace(from=" ", to="_")}}():
    """Scenario: {{scenario.name}}"""
    {% for step in scenario.steps -%}
    # {{step.keyword}} {{step.value}}
    {% endfor -%}
    assert True, "Auto-generated test from Grepkin Features!"
{# Another empty line to make legit py function delimitation = 2 lines #}
{% endfor %}
