// Test auto-generated by Grepkin, referencing a Gherkin feature file
{% if feature.path is defined -%}
// From reference feature-file at {{feature.path}}
{% endif -%}
//
{# Note: Tera is limited: split description on newlines, then prefix first with FEATURE kw and indent rest -#}
// Feature: {{feature.name}}
{%set descs = feature.description | split(pat="\n") -%}
{% for desc_line in descs-%}
//   {{desc_line}}
{% endfor -%}
{# Space out the feature and the scenarios=tests #}
{% for scenario in feature.scenarios -%}
/// Scenario: {{scenario.name}}
#[test]
fn test_generated_{{loop.index}}() {
    {% for step in scenario.steps -%}
    // {{step.keyword}} {{step.value}}
    {% endfor -%}
    assert!(true, "Auto-generated test from Grepkin Features!");
}

{% endfor -%}
